version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nyscraper
      POSTGRES_PASSWORD: nyscraper
      POSTGRES_DB: nyscraper
    ports:
      - 5432:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/




